import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "bg" | "en" | "el" | "tr" | "sr" | "mk" | "ro";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  bg: {
    // Hero Section
    heroTitle: "SkyParking - Паркинг Летище София",
    heroSubtitle: "Сигурен и достъпен паркинг на 5 минути от Терминал 1 и 2. Резервирайте сега и пътувайте със спокойствие.",
    bookNow: "Резервирай сега",
    callButton: "Обади се +359 886 616 991",
    
    // Navigation
    navFeatures: "Предимства",
    navBooking: "Резервация",
    navContact: "Контакти",
    navLocation: "Локация",
    navServices: "Услуги",
    navPricing: "Цени",
    navHowItWorks: "Как работи",
    navFAQ: "Често задавани въпроси",
    navAbout: "За нас",
    callNow: "Обади се",
    
    // Features
    whyChooseUs: "Защо да изберете SkyParking?",
    whyChooseUsDesc: "Предлагаме най-надеждното и удобно решение за паркиране за пътници от Летище София",
    secureParking: "Охраняем паркинг 24/7",
    secureParkingDesc: "Видеонаблюдение + жива охрана - автомобилът Ви е в сигурни ръце",
    flexibleHours: "Лесна резервация, без предплащане",
    flexibleHoursDesc: "Плащате при пристигане — без допълнителни такси или скрити изненади.",
    airportShuttle: "Безплатен трансфер до и от Летище София",
    airportShuttleDesc: "Бърз и удобен — само 5 минути до Терминал 1 и 2.",
    allVehicles: "Всички превозни средства",
    allVehiclesDesc: "Приемаме автомобили, ванове и джипове",
    lowPricesEasyBooking: "Ниски цени",
    lowPricesEasyBookingDesc: "Достъпни цени за краткосрочен и дългосрочен престой",
    
    // Booking Form
    bookYourSpot: "Запазете Вашето Място",
    reservation: "Резервация",
    reservationSubtitle: "Без предплащане · Потвърждение по телефон",
    bookYourParking: "Резервирайте вашия паркинг",
    datesAndTimes: "Дати и часове",
    yourParkingCost: "Вашата цена за паркинг",
    reservationSummary: "Обобщение на резервацията",
    duration: "Продължителност",
    totalCost: "Обща сума",
    noPrePayment: "Без предплащане – плащате при пристигане",
    processing: "Обработка...",
    fillDetails: "Попълнете данните по-долу и осигурете вашето място за паркиране",
    arrivalDate: "От дата",
    arrivalTime: "От час",
    departureDate: "До дата",
    departureTime: "До час",
    estimatedTotal: "Очаквана сума",
    finalTotal: "Крайна сума",
    priceIncludesTransfers: "Цена с включени безплатни трансфери",
    days: "дни",
    personalInfo: "Лична информация",
    fullName: "Пълно име",
    email: "Имейл",
    phone: "Телефонен номер",
    licensePlate: "Регистрационен номер",
    passengers: "Брой пътници",
    proceedToPayment: "Потвърди резервация",
    numberOfCars: "Брой автомобили",
    car: "автомобил",
    cars: "автомобила",
    perCar: "на кола",
    selectNumberOfCars: "Изберете колко автомобила ще паркирате (за големи групи или фирмени резервации)",
    vehicleInformation: "Информация за превозните средства",
    passenger: "пътник",
    passengersLabel: "пътници",
    selectTime: "Изберете час",
    timesApproximateHelp: "ℹ️ Часовете са ориентировъчни.\nАко пристигнете по-рано или по-късно, няма проблем – просто ни се обадете.",
    termsAndConditions: "Общи условия",
    termsAndConditionsLink: "Общите условия",
    agreeToTerms: "Съгласявам се с",
    termsRequired: "Трябва да се съгласите с общите условия",
    
    // Form Placeholders
    namePlaceholder: "Иван Петров",
    emailPlaceholder: "ivan@example.com",
    phonePlaceholder: "+359 888 123 456",
    licensePlatePlaceholder: "СВ 1234 АВ",
    
    // Validation Messages
    arrivalDateRequired: "Дата на пристигане е задължителна",
    arrivalTimeRequired: "Час на пристигане е задължителен",
    departureDateRequired: "Дата на заминаване е задължителна",
    departureTimeRequired: "Час на заминаване е задължителен",
    nameRequired: "Име е задължително",
    emailRequired: "Имейл е задължиелен",
    emailInvalid: "Невалиден имейл адрес",
    phoneRequired: "Телефонен номер е задължителен",
    phoneInvalid: "Телефонният номер може да съдържа само цифри и + за код на държава (макс. 15 символа)",
    licensePlateRequired: "Регистрационен номер е задължителен",
    passengersRequired: "Брой пътници е задължителен",
    passengersMin: "Минимум 1 пътник",
    passengersMax: "Максимум 8 пътници",
    
    // Invoice Fields
    needInvoice: "Необходима ли ви е фактура?",
    yes: "Да",
    no: "Не",
    invoiceDetails: "Данни за фактура",
    companyName: "Име на фирма",
    companyNamePlaceholder: "ООД ПРИМЕРНА ФИРМА",
    companyNameRequired: "Име на фирма е задължително",
    companyOwner: "Управител",
    companyOwnerPlaceholder: "Иван Петров",
    companyOwnerRequired: "Управител е задължителен",
    taxNumber: "ЕИК / Булстат",
    taxNumberPlaceholder: "123456789",
    taxNumberRequired: "ЕИК е задължителен",
    isVAT: "Регистриран по ДДС",
    vatNumber: "С номер",
    vatNumberPlaceholder: "BG123456789",
    vatNumberRequired: "ДДС номер е задължителен",
    autoGeneratedVAT: "Автоматично генериран ДДС номер на базата на ЕИК",
    enterTaxNumberFirst: "Моля, въведете ЕИК номер по-горе, за да бъде генериран ДДС номер",
    city: "Град",
    selectCity: "Изберете град",
    cityRequired: "Град е задължителен",
    address: "Адрес",
    addressPlaceholder: "ул. Примерна 123",
    addressRequired: "Адрес е задължителен",
    
    // Contact Form
    haveQuestions: "Имате въпроси?",
    inquiryDesc: "Изпратете ни вашето запитване и ще тговорим възможно най-скоро",
    name: "Име",
    phoneOptional: "Телефонен номер (по избор)",
    message: "Съобщение",
    sendInquiry: "Изпрати запитване",
    messagePlaceholder: "Как можем да ви помогнем?",
    messageRequired: "Съобщение е задължително",
    orContactDirectly: "Или се свържете с нас директно:",
    
    // Discount Code
    discountCode: "Промо код",
    discountCodePlaceholder: "Въведете промо код",
    discountCodeRequired: "Моля, въведете промо код",
    apply: "Приложи",
    validating: "Проверка...",
    discountApplied: "Промо код приложен! Отстъпка:",
    discount: "отстъпка",
    
    // Toast Messages
    checkDates: "Моля, проверете дтите и часовете",
    bookingConfirmed: "Резервация потвърдена! Сума: €",
    paymentProcessing: ". Обработка на плащането...",
    inquirySuccess: "Благодарим за вашето запитване! Ще се свържем с вас скоро.",
    spamProtection: "Моля, изчакайте малко преди да изпратите формата отново.",
    
    // Footer
    footerTagline: "Сигурно и достъпно паркинг решение за вашия автомобил",
    footerLocation: "📍 Улица Неделчо Бончев 30",
    footerRights: "© 2026 SkyParking - Паркинг Летище София. Всички права запазени.",
    
    // Map Section
    ourLocation: "Нашата локация",
    findUs: "Намерете ни лесно до Терминал 2 на Летище София",
    takeMeThere: "Навигирай ме",
    takeMeThereWaze: "Навигирай ме с Waze",
    googleMaps: "Google Maps",
    waze: "Waze",
    howToFindUs: "Как да ни откриете",
    
    // How It Works Section
    howItWorks: "Как работи?",
    onlineTelephoneBooking: "Онлайн / Телефонна резервция",
    onlineTelephoneBookingText1: "Можете да направите резервация като ни се обадите на",
    onlineTelephoneBookingText2: "или като попълните",
    onlineTelephoneBookingText3: ". След като завършите резервацията, ще получите обаждане от нас, за да потвърдим всички ваши данни.",
    bookingForm: "формата за резервация",
    arrivalAndTransfer: "Пристигане на паркинга и трансфер до летището",
    arrivalAndTransferDesc: "При пристигане ще бъдете посрещнати от нашия персонал, който ще ви помогне с багажа и паркирането на вашия автомобил. След това ще вземете включения трансфер до Летище София на терминала по ваш избор - и двата са на 5 минути от нашия паркинг.",
    returnAndPickup: "Връщане и напускане на паркинга",
    returnAndPickupText1: "Когато напуснете терминала и пристигнете до обособеното място за трансфер,",
    returnAndPickupText2: " и един от нашите бусове ще дойде ви вземе. Ще ви отведем до паркинга, където ще ви чака вашият автомобил.",
    callUs: "обадете ни се",
  },
  en: {
    // Hero Section
    heroTitle: "SkyParking - Sofia Airport Parking",
    heroSubtitle: "Secure, affordable parking 5 minutes from Terminal 1 and 2. Book now and travel with peace of mind.",
    bookNow: "Book Now",
    callButton: "Call +359 886 616 991",
    
    // Navigation
    navFeatures: "Features",
    navBooking: "Booking",
    navContact: "Contact",
    navLocation: "Location",
    navServices: "Services",
    navPricing: "Pricing",
    navHowItWorks: "How It Works",
    navFAQ: "FAQ",
    navAbout: "About Us",
    callNow: "Call Now",
    
    // Features
    whyChooseUs: "Why Choose SkyParking?",
    whyChooseUsDesc: "We provide the most reliable and convenient parking solution for Sofia Airport travelers",
    secureParking: "Secure parking 24/7",
    secureParkingDesc: "Video surveillance + on-site security — your car is safe at all times.",
    flexibleHours: "Easy booking, no prepayment",
    flexibleHoursDesc: "Pay on arrival — no extra fees or hidden surprises.",
    airportShuttle: "Free transfer to and from Sofia Airport",
    airportShuttleDesc: "Fast and convenient — just 5 minutes to Terminal 1 and 2.",
    allVehicles: "All Vehicles",
    allVehiclesDesc: "We accommodate cars, vans, and SUVs",
    lowPricesEasyBooking: "Low Prices",
    lowPricesEasyBookingDesc: "Affordable rates for short and long stays.",
    
    // Booking Form
    bookYourSpot: "Book Now",
    reservation: "Reservation",
    reservationSubtitle: "No Prepayment · Confirmation by Phone",
    bookYourParking: "Book Your Parking",
    datesAndTimes: "Dates and Times",
    yourParkingCost: "Your Parking Cost",
    reservationSummary: "Reservation Summary",
    duration: "Duration",
    totalCost: "Total Cost",
    noPrePayment: "No Prepayment – Pay on Arrival",
    processing: "Processing...",
    fillDetails: "Fill in your details below and secure your parking spot",
    arrivalDate: "From Date",
    arrivalTime: "From Time",
    departureDate: "To Date",
    departureTime: "To Time",
    estimatedTotal: "Estimated Total",
    finalTotal: "Final Total",
    priceIncludesTransfers: "Price includes free shuttles",
    days: "days",
    personalInfo: "Personal Information",
    fullName: "Full Name",
    email: "Email",
    phone: "Phone Number",
    licensePlate: "License Plate",
    passengers: "Number of Passengers",
    proceedToPayment: "Confirm Reservation",
    numberOfCars: "Number of Cars",
    car: "car",
    cars: "cars",
    perCar: "per car",
    selectNumberOfCars: "Select how many cars you will park (for large groups or corporate reservations)",
    vehicleInformation: "Vehicle Information",
    passenger: "passenger",
    passengersLabel: "passengers",
    selectTime: "Select time",
    timesApproximateHelp: "ℹ️ Times are approximate.\nIf you arrive earlier or later, no problem – just call us.",
    termsAndConditions: "Terms and Conditions",
    termsAndConditionsLink: "Terms and Conditions",
    agreeToTerms: "I agree to the",
    termsRequired: "You must agree to the terms and conditions",
    
    // Form Placeholders
    namePlaceholder: "John Doe",
    emailPlaceholder: "john@example.com",
    phonePlaceholder: "+359 888 123 456",
    licensePlatePlaceholder: "CB 1234 AB",
    
    // Validation Messages
    arrivalDateRequired: "Arrival date is required",
    arrivalTimeRequired: "Arrival time is required",
    departureDateRequired: "Departure date is required",
    departureTimeRequired: "Departure time is required",
    nameRequired: "Name is required",
    emailRequired: "Email is required",
    emailInvalid: "Invalid email address",
    phoneRequired: "Phone number is required",
    phoneInvalid: "Phone number can only contain digits and + for country code (max. 15 characters)",
    licensePlateRequired: "License plate is required",
    passengersRequired: "Number of passengers is required",
    passengersMin: "At least 1 passenger required",
    passengersMax: "Maximum 8 passengers",
    
    // Invoice Fields
    needInvoice: "Do you need an invoice?",
    yes: "Yes",
    no: "No",
    invoiceDetails: "Invoice details",
    companyName: "Company Name",
    companyNamePlaceholder: "OOD EXAMPLE COMPANY",
    companyNameRequired: "Company name is required",
    companyOwner: "Owner",
    companyOwnerPlaceholder: "John Doe",
    companyOwnerRequired: "Owner is required",
    taxNumber: "EIK / Bulstat",
    taxNumberPlaceholder: "123456789",
    taxNumberRequired: "EIK is required",
    isVAT: "Registered for VAT",
    vatNumber: "VAT Number",
    vatNumberPlaceholder: "BG123456789",
    vatNumberRequired: "VAT number is required",
    autoGeneratedVAT: "Auto-generated VAT number based on EIK",
    enterTaxNumberFirst: "Please enter EIK number above to generate VAT number",
    city: "City",
    selectCity: "Select city",
    cityRequired: "City is required",
    address: "Address",
    addressPlaceholder: "ul. Example 123",
    addressRequired: "Address is required",
    
    // Contact Form
    haveQuestions: "Have Questions?",
    inquiryDesc: "Send us your inquiry and we'll respond as soon as possible",
    name: "Name",
    phoneOptional: "Phone Number (Optional)",
    message: "Message",
    sendInquiry: "Send Inquiry",
    messagePlaceholder: "How can we help you?",
    messageRequired: "Message is required",
    orContactDirectly: "Or contact us directly:",
    
    // Discount Code
    discountCode: "Promo Code",
    discountCodePlaceholder: "Enter promo code",
    discountCodeRequired: "Please enter a promo code",
    apply: "Apply",
    validating: "Validating...",
    discountApplied: "Promo code applied! Discount:",
    discount: "discount",
    
    // Toast Messages
    checkDates: "Please check your dates and times",
    bookingConfirmed: "Booking confirmed! Total: €",
    paymentProcessing: ". Payment processing...",
    inquirySuccess: "Thank you for your inquiry! We'll get back to you shortly.",
    spamProtection: "Please wait a moment before submitting the form again.",
    
    // Footer
    footerTagline: "Secure, affordable, and convenient parking solutions",
    footerLocation: "📍 Ulitsa Nedelcho Bonchev 30",
    footerRights: "© 2026 SkyParking - Sofia Airport Parking. All rights reserved.",
    
    // Map Section
    ourLocation: "Our Location",
    findUs: "Find us easily near Terminal 2 at Sofia Airport",
    takeMeThere: "Take Me There",
    takeMeThereWaze: "Navigate with Waze",
    googleMaps: "Google Maps",
    waze: "Waze",
    howToFindUs: "How to Find Us",
    
    // How It Works Section
    howItWorks: "How It Works?",
    onlineTelephoneBooking: "Online / Telephone Booking",
    onlineTelephoneBookingText1: "You can make a reservation by calling us at",
    onlineTelephoneBookingText2: "or by filling out",
    onlineTelephoneBookingText3: ". After completing the reservation, we will call you to confirm all your details.",
    bookingForm: "the booking form",
    arrivalAndTransfer: "Arrival at the parking and transfer to the airport",
    arrivalAndTransferDesc: "Upon arrival, you will be greeted by our staff who will help you with your luggage and parking your car. Then you will take the included shuttle to Sofia Airport at the terminal of your choice - both are 5 minutes from our parking.",
    returnAndPickup: "Return and leaving the parking",
    returnAndPickupText1: "When you leave the terminal and arrive at the designated transfer area,",
    returnAndPickupText2: " and one of our shuttle buses will come to pick you up. We will take you to the parking lot where your car will be waiting for you.",
    callUs: "call us",
  },
  el: {
    // Hero Section
    heroTitle: "SkyParking - Πάρκινγκ Αεροδρόμιο Σόφιας",
    heroSubtitle: "Ασφαλές και προσιτό πάρκινγκ 5 λεπτά από Τερματικό 1 και 2. Κάντε κράτηση τώρα και ταξιδέψτε αναπαυτικά.",
    bookNow: "Κράτηση Τώρα",
    callButton: "Καλέστε +359 886 616 991",

    // Navigation
    navFeatures: "Πλεονεκτήματα",
    navBooking: "Κράτηση",
    navContact: "Επικοινωνία",
    navLocation: "Τοποθεσία",
    navServices: "Υπηρεσίες",
    navPricing: "Τιμές",
    navHowItWorks: "Πώς Λειτουργεί",
    navFAQ: "Συχνές Ερωτήσεις",
    navAbout: "Σχετικά με Εμάς",
    callNow: "Καλέστε",

    // Features
    whyChooseUs: "Γιατί να επιλέξετε το SkyParking;",
    whyChooseUsDesc: "Παρέχουμε την πιο αξιόπιστη και βολική λύση στάθμευσης για επιβάτες του Αεροδρομίου της Σόφιας",
    secureParking: "Ασφαλής στάθμευση 24/7",
    secureParkingDesc: "Βιντεοεπιτήρηση + επί τόπου φύλαξη — το αυτοκίνητό σας είναι πάντα ασφαλές.",
    flexibleHours: "Εύκολη κράτηση, χωρίς προκαταβολή",
    flexibleHoursDesc: "Πληρώνετε κατά την άφιξη — χωρίς επιπλέον χρεώσεις ή κρυφές εκπλήξεις.",
    airportShuttle: "Δωρεάν μεταφορά από και προς το Αεροδρόμιο της Σόφιας",
    airportShuttleDesc: "Γρήγορο και βολικό — μόλις 5 λεπτά έως Τερματικό 1 και 2.",
    allVehicles: "Όλα τα οχήματα",
    allVehiclesDesc: "Δεχόμαστε αυτοκίνητα, βαν και SUV",
    lowPricesEasyBooking: "Χαμηλές Τιμές",
    lowPricesEasyBookingDesc: "Προσιτές τιμές για βραχυπρόθεσμη και μακροπρόθεσμη παραμονή.",

    // Booking Form
    bookYourSpot: "Κάντε Κράτηση",
    reservation: "Κράτηση",
    reservationSubtitle: "Χωρίς Προκαταβολή · Επιβεβαίωση Τηλεφωνικώς",
    bookYourParking: "Κράτηση Χώρου Στάθμευσης",
    datesAndTimes: "Ημερομηνίες και Ώρες",
    yourParkingCost: "Κόστος Στάθμευσης",
    reservationSummary: "Σύνοψη Κράτησης",
    duration: "Διάρκεια",
    totalCost: "Συνολικό Κόστος",
    noPrePayment: "Χωρίς Προκαταβολή – Πληρώνετε κατά την Άφιξη",
    processing: "Επεξεργασία...",
    fillDetails: "Συμπληρώστε τα στοιχεία σας παρακάτω και εξασφαλίστε τη θέση στάθμευσής σας",
    arrivalDate: "Από Ημερομηνία",
    arrivalTime: "Από Ώρα",
    departureDate: "Έως Ημερομηνία",
    departureTime: "Έως Ώρα",
    estimatedTotal: "Εκτιμώμενο Σύνολο",
    finalTotal: "Τελικό Σύνολο",
    priceIncludesTransfers: "Η τιμή περιλαμβάνει δωρεάν μεταφορές",
    days: "ημέρες",
    personalInfo: "Προσωπικές Πληροφορίες",
    fullName: "Πλήρες Όνομα",
    email: "Email",
    phone: "Αριθμός Τηλεφώνου",
    licensePlate: "Πινακίδα Κυκλοφορίας",
    passengers: "Αριθμός Επιβατών",
    proceedToPayment: "Επιβεβαίωση Κράτησης",
    numberOfCars: "Αριθμός Αυτοκινήτων",
    car: "αυτοκίνητο",
    cars: "αυτοκίνητα",
    perCar: "ανά αυτοκίνητο",
    selectNumberOfCars: "Επιλέξτε πόσα αυτοκίνητα θα σταθμεύσετε (για μεγάλες ομάδες ή εταιρικές κρατήσεις)",
    vehicleInformation: "Πληροφορίες Οχήματος",
    passenger: "επιβάτης",
    passengersLabel: "επιβάτες",
    selectTime: "Επιλέξτε ώρα",
    timesApproximateHelp: "ℹ️ Οι ώρες είναι κατά προσέγγιση.\nΑν φτάσετε νωρίτερα ή αργότερα, δεν υπάρχει πρόβλημα – απλά καλέστε μας.",
    termsAndConditions: "Όροι και Προϋποθέσεις",
    termsAndConditionsLink: "Όρους και Προϋποθέσεις",
    agreeToTerms: "Συμφωνώ με τους",
    termsRequired: "Πρέπει να αποδεχθείτε τους όρους και τις προϋποθέσεις",

    // Form Placeholders
    namePlaceholder: "Γιώργος Παπαδόπουλος",
    emailPlaceholder: "giorgos@example.com",
    phonePlaceholder: "+30 693 123 4567",
    licensePlatePlaceholder: "ABC-1234",

    // Validation Messages
    arrivalDateRequired: "Η ημερομηνία άφιξης είναι υποχρεωτική",
    arrivalTimeRequired: "Η ώρα άφιξης είναι υποχρεωτική",
    departureDateRequired: "Η ημερομηνία αναχώρησης είναι υποχρεωτική",
    departureTimeRequired: "Η ώρα αναχώρησης είναι υποχρεωτική",
    nameRequired: "Το όνομα είναι υποχρεωτικό",
    emailRequired: "Το email είναι υποχρεωτικό",
    emailInvalid: "Μη έγκυρη διεύθυνση email",
    phoneRequired: "Ο αριθμός τηλεφώνου είναι υποχρεωτικός",
    phoneInvalid: "Ο αριθμός τηλεφώνου μπορεί να περιέχει μόνο ψηφία και + για κωδικό χώρας (μέγ. 15 χαρακτήρες)",
    licensePlateRequired: "Η πινακίδα κυκλοφορίας είναι υποχρεωτική",
    passengersRequired: "Ο αριθμός επιβατών είναι υποχρεωτικός",
    passengersMin: "Τουλάχιστον 1 επιβάτης",
    passengersMax: "Μέγιστο 8 επιβάτες",

    // Invoice Fields
    needInvoice: "Χρειάζεστε τιμολόγιο;",
    yes: "Ναι",
    no: "Όχι",
    invoiceDetails: "Στοιχεία Τιμολογίου",
    companyName: "Επωνυμία Εταιρείας",
    companyNamePlaceholder: "ΠΑΡΑΔΕΙΓΜΑ ΑΕ",
    companyNameRequired: "Η επωνυμία εταιρείας είναι υποχρεωτική",
    companyOwner: "Νόμιμος Εκπρόσωπος",
    companyOwnerPlaceholder: "Γιώργος Παπαδόπουλος",
    companyOwnerRequired: "Ο νόμιμος εκπρόσωπος είναι υποχρεωτικός",
    taxNumber: "ΑΦΜ",
    taxNumberPlaceholder: "123456789",
    taxNumberRequired: "Το ΑΦΜ είναι υποχρεωτικό",
    isVAT: "Εγγεγραμμένος στο ΦΠΑ",
    vatNumber: "Αριθμός ΦΠΑ",
    vatNumberPlaceholder: "EL123456789",
    vatNumberRequired: "Ο αριθμός ΦΠΑ είναι υποχρεωτικός",
    autoGeneratedVAT: "Αυτόματα παραγόμενος αριθμός ΦΠΑ βάσει ΑΦΜ",
    enterTaxNumberFirst: "Παρακαλώ εισάγετε ΑΦΜ παραπάνω για να παραχθεί αριθμός ΦΠΑ",
    city: "Πόλη",
    selectCity: "Επιλέξτε πόλη",
    cityRequired: "Η πόλη είναι υποχρεωτική",
    address: "Διεύθυνση",
    addressPlaceholder: "οδ. Παράδειγμα 123",
    addressRequired: "Η διεύθυνση είναι υποχρεωτική",

    // Contact Form
    haveQuestions: "Έχετε Ερωτήσεις;",
    inquiryDesc: "Στείλτε μας το ερώτημά σας και θα απαντήσουμε το συντομότερο δυνατό",
    name: "Όνομα",
    phoneOptional: "Αριθμός Τηλεφώνου (Προαιρετικό)",
    message: "Μήνυμα",
    sendInquiry: "Αποστολή Ερωτήματος",
    messagePlaceholder: "Πώς μπορούμε να σας βοηθήσουμε;",
    messageRequired: "Το μήνυμα είναι υποχρεωτικό",
    orContactDirectly: "Ή επικοινωνήστε μαζί μας απευθείας:",

    // Discount Code
    discountCode: "Κωδικός Προσφοράς",
    discountCodePlaceholder: "Εισάγετε κωδικό προσφοράς",
    discountCodeRequired: "Παρακαλώ εισάγετε κωδικό προσφοράς",
    apply: "Εφαρμογή",
    validating: "Επαλήθευση...",
    discountApplied: "Κωδικός εφαρμόστηκε! Έκπτωση:",
    discount: "έκπτωση",

    // Toast Messages
    checkDates: "Παρακαλώ ελέγξτε τις ημερομηνίες και ώρες σας",
    bookingConfirmed: "Κράτηση επιβεβαιώθηκε! Σύνολο: €",
    paymentProcessing: ". Επεξεργασία πληρωμής...",
    inquirySuccess: "Ευχαριστούμε για το ερώτημά σας! Θα επικοινωνήσουμε μαζί σας σύντομα.",
    spamProtection: "Παρακαλώ περιμένετε λίγο πριν υποβάλετε ξανά τη φόρμα.",

    // Footer
    footerTagline: "Ασφαλής, προσιτή και βολική λύση στάθμευσης",
    footerLocation: "📍 Ulitsa Nedelcho Bonchev 30, Σόφια",
    footerRights: "© 2026 SkyParking - Πάρκινγκ Αεροδρόμιο Σόφιας. Όλα τα δικαιώματα διατηρούνται.",

    // Map Section
    ourLocation: "Η Τοποθεσία Μας",
    findUs: "Βρείτε μας εύκολα κοντά στο Τερματικό 2 του Αεροδρομίου της Σόφιας",
    takeMeThere: "Πήγαινέ με Εκεί",
    takeMeThereWaze: "Πλοήγηση με Waze",
    googleMaps: "Google Maps",
    waze: "Waze",
    howToFindUs: "Πώς να μας βρείτε",

    // How It Works Section
    howItWorks: "Πώς Λειτουργεί;",
    onlineTelephoneBooking: "Online / Τηλεφωνική Κράτηση",
    onlineTelephoneBookingText1: "Μπορείτε να κάνετε κράτηση καλώντας μας στο",
    onlineTelephoneBookingText2: "ή συμπληρώνοντας",
    onlineTelephoneBookingText3: ". Μετά την ολοκλήρωση της κράτησης, θα σας καλέσουμε για να επιβεβαιώσουμε τα στοιχεία σας.",
    bookingForm: "τη φόρμα κράτησης",
    arrivalAndTransfer: "Άφιξη στο πάρκινγκ και μεταφορά στο αεροδρόμιο",
    arrivalAndTransferDesc: "Κατά την άφιξη, το προσωπικό μας θα σας υποδεχθεί και θα σας βοηθήσει με τις αποσκευές και τη στάθμευση. Στη συνέχεια θα πάρετε την περιλαμβανόμενη μεταφορά στο Αεροδρόμιο της Σόφιας — και τα δύο τερματικά απέχουν μόλις 5 λεπτά.",
    returnAndPickup: "Επιστροφή και αναχώρηση από το πάρκινγκ",
    returnAndPickupText1: "Όταν αναχωρήσετε από το τερματικό και φτάσετε στον καθορισμένο χώρο μεταφοράς,",
    returnAndPickupText2: " και ένα από τα λεωφορεία μας θα έρθει να σας παραλάβει. Θα σας μεταφέρουμε στο πάρκινγκ όπου θα σας περιμένει το αυτοκίνητό σας.",
    callUs: "καλέστε μας",
  },
  tr: {
    // Hero Section
    heroTitle: "SkyParking - Sofya Havalimanı Otoparkı",
    heroSubtitle: "Terminal 1 ve 2'ye 5 dakika uzaklıkta güvenli ve uygun fiyatlı otopark. Şimdi rezervasyon yapın, huzurla seyahat edin.",
    bookNow: "Şimdi Rezervasyon Yap",
    callButton: "Ara +359 886 616 991",

    // Navigation
    navFeatures: "Avantajlar",
    navBooking: "Rezervasyon",
    navContact: "İletişim",
    navLocation: "Konum",
    navServices: "Hizmetler",
    navPricing: "Fiyatlar",
    navHowItWorks: "Nasıl Çalışır",
    navFAQ: "Sık Sorulan Sorular",
    navAbout: "Hakkımızda",
    callNow: "Şimdi Ara",

    // Features
    whyChooseUs: "Neden SkyParking'i Seçmelisiniz?",
    whyChooseUsDesc: "Sofya Havalimanı yolcuları için en güvenilir ve pratik otopark çözümünü sunuyoruz",
    secureParking: "7/24 Güvenli Otopark",
    secureParkingDesc: "Kamera sistemi + yerinde güvenlik — araçınız her zaman güvende.",
    flexibleHours: "Kolay rezervasyon, ön ödeme yok",
    flexibleHoursDesc: "Gelişte ödeyin — ekstra ücret veya gizli sürpriz yok.",
    airportShuttle: "Sofya Havalimanı'na Ücretsiz Servis",
    airportShuttleDesc: "Hızlı ve pratik — Terminal 1 ve 2'ye sadece 5 dakika.",
    allVehicles: "Tüm Araçlar",
    allVehiclesDesc: "Binek araç, minibüs ve SUV kabul ediyoruz",
    lowPricesEasyBooking: "Uygun Fiyatlar",
    lowPricesEasyBookingDesc: "Kısa ve uzun süreli konaklamalar için uygun fiyatlar.",

    // Booking Form
    bookYourSpot: "Rezervasyon Yap",
    reservation: "Rezervasyon",
    reservationSubtitle: "Ön Ödeme Yok · Telefonla Onay",
    bookYourParking: "Otoparkınızı Rezerve Edin",
    datesAndTimes: "Tarihler ve Saatler",
    yourParkingCost: "Otopark Ücretiniz",
    reservationSummary: "Rezervasyon Özeti",
    duration: "Süre",
    totalCost: "Toplam Ücret",
    noPrePayment: "Ön Ödeme Yok – Gelişte Ödeyin",
    processing: "İşleniyor...",
    fillDetails: "Aşağıdaki bilgileri doldurun ve otopark yerinizi garantileyin",
    arrivalDate: "Giriş Tarihi",
    arrivalTime: "Giriş Saati",
    departureDate: "Çıkış Tarihi",
    departureTime: "Çıkış Saati",
    estimatedTotal: "Tahmini Toplam",
    finalTotal: "Toplam",
    priceIncludesTransfers: "Fiyata ücretsiz servis dahildir",
    days: "gün",
    personalInfo: "Kişisel Bilgiler",
    fullName: "Ad Soyad",
    email: "E-posta",
    phone: "Telefon Numarası",
    licensePlate: "Plaka",
    passengers: "Yolcu Sayısı",
    proceedToPayment: "Rezervasyonu Onayla",
    numberOfCars: "Araç Sayısı",
    car: "araç",
    cars: "araç",
    perCar: "araç başına",
    selectNumberOfCars: "Kaç araç park edeceğinizi seçin (büyük gruplar veya kurumsal rezervasyonlar için)",
    vehicleInformation: "Araç Bilgileri",
    passenger: "yolcu",
    passengersLabel: "yolcu",
    selectTime: "Saat seçin",
    timesApproximateHelp: "ℹ️ Saatler yaklaşık değerdir.\nErken veya geç gelirseniz sorun yok – sadece bizi arayın.",
    termsAndConditions: "Kullanım Koşulları",
    termsAndConditionsLink: "Kullanım Koşullarını",
    agreeToTerms: "Kabul ediyorum",
    termsRequired: "Kullanım koşullarını kabul etmelisiniz",

    // Form Placeholders
    namePlaceholder: "Ahmet Yılmaz",
    emailPlaceholder: "ahmet@example.com",
    phonePlaceholder: "+90 532 123 4567",
    licensePlatePlaceholder: "34 ABC 123",

    // Validation Messages
    arrivalDateRequired: "Giriş tarihi zorunludur",
    arrivalTimeRequired: "Giriş saati zorunludur",
    departureDateRequired: "Çıkış tarihi zorunludur",
    departureTimeRequired: "Çıkış saati zorunludur",
    nameRequired: "Ad zorunludur",
    emailRequired: "E-posta zorunludur",
    emailInvalid: "Geçersiz e-posta adresi",
    phoneRequired: "Telefon numarası zorunludur",
    phoneInvalid: "Telefon numarası yalnızca rakam ve ülke kodu için + içerebilir (maks. 15 karakter)",
    licensePlateRequired: "Plaka zorunludur",
    passengersRequired: "Yolcu sayısı zorunludur",
    passengersMin: "En az 1 yolcu gereklidir",
    passengersMax: "Maksimum 8 yolcu",

    // Invoice Fields
    needInvoice: "Fatura gerekiyor mu?",
    yes: "Evet",
    no: "Hayır",
    invoiceDetails: "Fatura Bilgileri",
    companyName: "Şirket Adı",
    companyNamePlaceholder: "ÖRNEK ŞİRKET LTD",
    companyNameRequired: "Şirket adı zorunludur",
    companyOwner: "Yetkili Kişi",
    companyOwnerPlaceholder: "Ahmet Yılmaz",
    companyOwnerRequired: "Yetkili kişi zorunludur",
    taxNumber: "Vergi No",
    taxNumberPlaceholder: "123456789",
    taxNumberRequired: "Vergi numarası zorunludur",
    isVAT: "KDV Mükellefi",
    vatNumber: "KDV Numarası",
    vatNumberPlaceholder: "TR123456789",
    vatNumberRequired: "KDV numarası zorunludur",
    autoGeneratedVAT: "Vergi numarasına göre otomatik oluşturulan KDV numarası",
    enterTaxNumberFirst: "KDV numarası oluşturmak için lütfen yukarıya vergi numarasını girin",
    city: "Şehir",
    selectCity: "Şehir seçin",
    cityRequired: "Şehir zorunludur",
    address: "Adres",
    addressPlaceholder: "Örnek Sokak 123",
    addressRequired: "Adres zorunludur",

    // Contact Form
    haveQuestions: "Sorularınız mı var?",
    inquiryDesc: "Bize sorunuzu gönderin, en kısa sürede yanıtlayacağız",
    name: "Ad",
    phoneOptional: "Telefon Numarası (İsteğe Bağlı)",
    message: "Mesaj",
    sendInquiry: "Soru Gönder",
    messagePlaceholder: "Size nasıl yardımcı olabiliriz?",
    messageRequired: "Mesaj zorunludur",
    orContactDirectly: "Ya da doğrudan bize ulaşın:",

    // Discount Code
    discountCode: "Promosyon Kodu",
    discountCodePlaceholder: "Promosyon kodu girin",
    discountCodeRequired: "Lütfen promosyon kodu girin",
    apply: "Uygula",
    validating: "Doğrulanıyor...",
    discountApplied: "Promosyon kodu uygulandı! İndirim:",
    discount: "indirim",

    // Toast Messages
    checkDates: "Lütfen tarih ve saatlerinizi kontrol edin",
    bookingConfirmed: "Rezervasyon onaylandı! Toplam: €",
    paymentProcessing: ". Ödeme işleniyor...",
    inquirySuccess: "Sorunuz için teşekkürler! En kısa sürede size döneceğiz.",
    spamProtection: "Lütfen formu tekrar göndermeden önce biraz bekleyin.",

    // Footer
    footerTagline: "Güvenli, uygun fiyatlı ve pratik otopark çözümleri",
    footerLocation: "📍 Ulitsa Nedelcho Bonchev 30, Sofya",
    footerRights: "© 2026 SkyParking - Sofya Havalimanı Otoparkı. Tüm hakları saklıdır.",

    // Map Section
    ourLocation: "Konumumuz",
    findUs: "Sofya Havalimanı Terminal 2 yakınında bizi kolayca bulun",
    takeMeThere: "Yol Tarifi Al",
    takeMeThereWaze: "Waze ile Yol Tarifi Al",
    googleMaps: "Google Maps",
    waze: "Waze",
    howToFindUs: "Bize Nasıl Ulaşılır",

    // How It Works Section
    howItWorks: "Nasıl Çalışır?",
    onlineTelephoneBooking: "Online / Telefon Rezervasyonu",
    onlineTelephoneBookingText1: "Bizi arayarak rezervasyon yapabilirsiniz",
    onlineTelephoneBookingText2: "veya",
    onlineTelephoneBookingText3: "doldurarak. Rezervasyon tamamlandıktan sonra sizi arayarak tüm bilgilerinizi onaylayacağız.",
    bookingForm: "rezervasyon formunu",
    arrivalAndTransfer: "Otoparka Varış ve Havalimanına Transfer",
    arrivalAndTransferDesc: "Varışınızda personeliniz sizi karşılayacak, bagajınıza yardımcı olacak ve aracınızı park edecek. Ardından tercih ettiğiniz terminale dahil servis ile aktarılacaksınız — her iki terminal de otoparkımıza sadece 5 dakika uzaklıktadır.",
    returnAndPickup: "Dönüş ve Otoparktan Ayrılış",
    returnAndPickupText1: "Terminalden ayrılıp belirlenen transfer alanına geldiğinizde,",
    returnAndPickupText2: " servis araçlarımızdan biri sizi almaya gelecektir. Sizi aracınızın beklediği otoparka götüreceğiz.",
    callUs: "bizi arayın",
  },
  sr: {
    // Hero Section
    heroTitle: "SkyParking - Parking Aerodrom Sofija",
    heroSubtitle: "Siguran i pristupačan parking 5 minuta od Terminala 1 i 2. Rezervišite sada i putujte bez brige.",
    bookNow: "Rezervišite Sada",
    callButton: "Pozovite +359 886 616 991",

    // Navigation
    navFeatures: "Prednosti",
    navBooking: "Rezervacija",
    navContact: "Kontakt",
    navLocation: "Lokacija",
    navServices: "Usluge",
    navPricing: "Cene",
    navHowItWorks: "Kako Funkcioniše",
    navFAQ: "Česta pitanja",
    navAbout: "O Nama",
    callNow: "Pozovite",

    // Features
    whyChooseUs: "Zašto izabrati SkyParking?",
    whyChooseUsDesc: "Pružamo najpouzdanije i najpogodnije rešenje za parkiranje za putnike Aerodroma Sofija",
    secureParking: "Siguran parking 24/7",
    secureParkingDesc: "Video nadzor + obezbeđenje — vaš automobil je uvek siguran.",
    flexibleHours: "Laka rezervacija, bez avansa",
    flexibleHoursDesc: "Plaćate pri dolasku — bez dodatnih naknada ili skrivenih iznenađenja.",
    airportShuttle: "Besplatan transfer do i od Aerodroma Sofija",
    airportShuttleDesc: "Brzo i pogodno — samo 5 minuta do Terminala 1 i 2.",
    allVehicles: "Sva vozila",
    allVehiclesDesc: "Prihvatamo automobile, kombije i džipove",
    lowPricesEasyBooking: "Niske Cene",
    lowPricesEasyBookingDesc: "Pristupačne cene za kratkoročni i dugoročni boravak.",

    // Booking Form
    bookYourSpot: "Rezervišite Mesto",
    reservation: "Rezervacija",
    reservationSubtitle: "Bez Avansa · Potvrda Telefonom",
    bookYourParking: "Rezervišite Vaš Parking",
    datesAndTimes: "Datumi i Vreme",
    yourParkingCost: "Vaša Cena Parkinga",
    reservationSummary: "Pregled Rezervacije",
    duration: "Trajanje",
    totalCost: "Ukupna Cena",
    noPrePayment: "Bez Avansa – Plaćate pri Dolasku",
    processing: "Obrada...",
    fillDetails: "Popunite podatke ispod i osigurajte svoje parking mesto",
    arrivalDate: "Od Datuma",
    arrivalTime: "Od Vremena",
    departureDate: "Do Datuma",
    departureTime: "Do Vremena",
    estimatedTotal: "Procenjena Suma",
    finalTotal: "Konačna Suma",
    priceIncludesTransfers: "Cena uključuje besplatan transfer",
    days: "dana",
    personalInfo: "Lični Podaci",
    fullName: "Puno Ime",
    email: "Email",
    phone: "Broj Telefona",
    licensePlate: "Registarska Tablica",
    passengers: "Broj Putnika",
    proceedToPayment: "Potvrdi Rezervaciju",
    numberOfCars: "Broj Automobila",
    car: "automobil",
    cars: "automobila",
    perCar: "po autu",
    selectNumberOfCars: "Izaberite koliko automobila ćete parkirati (za velike grupe ili korporativne rezervacije)",
    vehicleInformation: "Informacije o Vozilu",
    passenger: "putnik",
    passengersLabel: "putnika",
    selectTime: "Izaberite vreme",
    timesApproximateHelp: "ℹ️ Vremena su okvirna.\nAko dođete ranije ili kasnije, nema problema – samo nas pozovite.",
    termsAndConditions: "Uslovi Korišćenja",
    termsAndConditionsLink: "Uslovima Korišćenja",
    agreeToTerms: "Slažem se sa",
    termsRequired: "Morate prihvatiti uslove korišćenja",

    // Form Placeholders
    namePlaceholder: "Marko Nikolić",
    emailPlaceholder: "marko@example.com",
    phonePlaceholder: "+381 63 123 4567",
    licensePlatePlaceholder: "BG 123-AB",

    // Validation Messages
    arrivalDateRequired: "Datum dolaska je obavezan",
    arrivalTimeRequired: "Vreme dolaska je obavezno",
    departureDateRequired: "Datum odlaska je obavezan",
    departureTimeRequired: "Vreme odlaska je obavezno",
    nameRequired: "Ime je obavezno",
    emailRequired: "Email je obavezan",
    emailInvalid: "Nevažeća email adresa",
    phoneRequired: "Broj telefona je obavezan",
    phoneInvalid: "Broj telefona može sadržati samo cifre i + za pozivni broj (maks. 15 znakova)",
    licensePlateRequired: "Registarska tablica je obavezna",
    passengersRequired: "Broj putnika je obavezan",
    passengersMin: "Minimalno 1 putnik",
    passengersMax: "Maksimalno 8 putnika",

    // Invoice Fields
    needInvoice: "Trebate li fakturu?",
    yes: "Da",
    no: "Ne",
    invoiceDetails: "Podaci za Fakturu",
    companyName: "Naziv Kompanije",
    companyNamePlaceholder: "PRIMER D.O.O.",
    companyNameRequired: "Naziv kompanije je obavezan",
    companyOwner: "Direktor",
    companyOwnerPlaceholder: "Marko Nikolić",
    companyOwnerRequired: "Direktor je obavezan",
    taxNumber: "PIB",
    taxNumberPlaceholder: "123456789",
    taxNumberRequired: "PIB je obavezan",
    isVAT: "Registrovan za PDV",
    vatNumber: "PDV Broj",
    vatNumberPlaceholder: "RS123456789",
    vatNumberRequired: "PDV broj je obavezan",
    autoGeneratedVAT: "Automatski generisan PDV broj na osnovu PIB-a",
    enterTaxNumberFirst: "Molimo unesite PIB iznad da biste generisali PDV broj",
    city: "Grad",
    selectCity: "Izaberite grad",
    cityRequired: "Grad je obavezan",
    address: "Adresa",
    addressPlaceholder: "ul. Primer 123",
    addressRequired: "Adresa je obavezna",

    // Contact Form
    haveQuestions: "Imate pitanja?",
    inquiryDesc: "Pošaljite nam upit i odgovorićemo što pre",
    name: "Ime",
    phoneOptional: "Broj Telefona (Opciono)",
    message: "Poruka",
    sendInquiry: "Pošalji Upit",
    messagePlaceholder: "Kako možemo da vam pomognemo?",
    messageRequired: "Poruka je obavezna",
    orContactDirectly: "Ili nas kontaktirajte direktno:",

    // Discount Code
    discountCode: "Promo Kod",
    discountCodePlaceholder: "Unesite promo kod",
    discountCodeRequired: "Molimo unesite promo kod",
    apply: "Primeni",
    validating: "Provera...",
    discountApplied: "Promo kod primenjen! Popust:",
    discount: "popust",

    // Toast Messages
    checkDates: "Molimo proverite datume i vremena",
    bookingConfirmed: "Rezervacija potvrđena! Iznos: €",
    paymentProcessing: ". Obrada plaćanja...",
    inquirySuccess: "Hvala na upitu! Uskoro ćemo vam se javiti.",
    spamProtection: "Molimo sačekajte malo pre ponovnog slanja formulara.",

    // Footer
    footerTagline: "Sigurno, pristupačno i zgodno rešenje za parkiranje",
    footerLocation: "📍 Ulica Nedelčo Bončev 30, Sofija",
    footerRights: "© 2026 SkyParking - Parking Aerodrom Sofija. Sva prava zadržana.",

    // Map Section
    ourLocation: "Naša Lokacija",
    findUs: "Pronađite nas lako u blizini Terminala 2 Aerodroma Sofija",
    takeMeThere: "Navigiraj Me",
    takeMeThereWaze: "Navigiraj sa Waze",
    googleMaps: "Google Maps",
    waze: "Waze",
    howToFindUs: "Kako da nas pronađete",

    // How It Works Section
    howItWorks: "Kako Funkcioniše?",
    onlineTelephoneBooking: "Online / Telefonska Rezervacija",
    onlineTelephoneBookingText1: "Možete napraviti rezervaciju pozivanjem na",
    onlineTelephoneBookingText2: "ili popunjavanjem",
    onlineTelephoneBookingText3: ". Nakon završetka rezervacije, pozvat ćemo vas da potvrdimo sve vaše podatke.",
    bookingForm: "formulara za rezervaciju",
    arrivalAndTransfer: "Dolazak na parking i transfer do aerodroma",
    arrivalAndTransferDesc: "Po dolasku, naše osoblje će vas dočekati i pomoći vam sa prtljagom i parkiranjem vašeg automobila. Zatim ćete koristiti uključeni transfer do Aerodroma Sofija na terminalu po vašem izboru — oba su 5 minuta od našeg parkinga.",
    returnAndPickup: "Povratak i napuštanje parkinga",
    returnAndPickupText1: "Kada napustite terminal i dođete do određenog mesta za transfer,",
    returnAndPickupText2: " i jedan od naših autobusa doći će da vas pokupi. Odvest ćemo vas na parking gde će vas čekati vaš automobil.",
    callUs: "pozovite nas",
  },
  mk: {
    // Hero Section
    heroTitle: "SkyParking - Паркинг Аеродром Софија",
    heroSubtitle: "Безбеден и достапен паркинг 5 минути од Терминал 1 и 2. Резервирајте сега и патувајте мирно.",
    bookNow: "Резервирај Сега",
    callButton: "Јави се +359 886 616 991",

    // Navigation
    navFeatures: "Предности",
    navBooking: "Резервација",
    navContact: "Контакт",
    navLocation: "Локација",
    navServices: "Услуги",
    navPricing: "Цени",
    navHowItWorks: "Како Функционира",
    navFAQ: "Чести прашања",
    navAbout: "За Нас",
    callNow: "Јави се",

    // Features
    whyChooseUs: "Зошто да изберете SkyParking?",
    whyChooseUsDesc: "Обезбедуваме најдоверливо и најпогодно решение за паркирање за патниците на Аеродром Софија",
    secureParking: "Безбеден паркинг 24/7",
    secureParkingDesc: "Видеонадзор + обезбедување — вашиот автомобил е секогаш безбеден.",
    flexibleHours: "Лесна резервација, без аванс",
    flexibleHoursDesc: "Плаќате при пристигање — без дополнителни надоместоци или скриени изненадувања.",
    airportShuttle: "Бесплатен трансфер до и од Аеродром Софија",
    airportShuttleDesc: "Брзо и погодно — само 5 минути до Терминал 1 и 2.",
    allVehicles: "Сите возила",
    allVehiclesDesc: "Прифаќаме автомобили, комбиња и џипови",
    lowPricesEasyBooking: "Ниски Цени",
    lowPricesEasyBookingDesc: "Достапни цени за краткорочен и долгорочен престој.",

    // Booking Form
    bookYourSpot: "Резервирај Место",
    reservation: "Резервација",
    reservationSubtitle: "Без Аванс · Потврда по Телефон",
    bookYourParking: "Резервирај го твојот паркинг",
    datesAndTimes: "Датуми и Времиња",
    yourParkingCost: "Вашата Цена за Паркинг",
    reservationSummary: "Преглед на Резервацијата",
    duration: "Траење",
    totalCost: "Вкупна Цена",
    noPrePayment: "Без Аванс – Плаќате при Пристигање",
    processing: "Обработка...",
    fillDetails: "Пополнете ги деталите подолу и осигурајте го вашето паркинг место",
    arrivalDate: "Од Датум",
    arrivalTime: "Од Час",
    departureDate: "До Датум",
    departureTime: "До Час",
    estimatedTotal: "Проценет Износ",
    finalTotal: "Краен Износ",
    priceIncludesTransfers: "Цената вклучува бесплатен трансфер",
    days: "денови",
    personalInfo: "Лични Информации",
    fullName: "Полно Име",
    email: "Е-пошта",
    phone: "Телефонски Број",
    licensePlate: "Регистарска Таблица",
    passengers: "Број на Патници",
    proceedToPayment: "Потврди Резервација",
    numberOfCars: "Број на Автомобили",
    car: "автомобил",
    cars: "автомобили",
    perCar: "по автомобил",
    selectNumberOfCars: "Изберете колку автомобили ќе паркирате (за големи групи или корпоративни резервации)",
    vehicleInformation: "Информации за Возилото",
    passenger: "патник",
    passengersLabel: "патници",
    selectTime: "Изберете час",
    timesApproximateHelp: "ℹ️ Времињата се приближни.\nАко пристигнете порано или покасно, нема проблем – само јавете ни се.",
    termsAndConditions: "Општи Услови",
    termsAndConditionsLink: "Општите Услови",
    agreeToTerms: "Се согласувам со",
    termsRequired: "Мора да ги прифатите општите услови",

    // Form Placeholders
    namePlaceholder: "Марко Петровски",
    emailPlaceholder: "marko@example.com",
    phonePlaceholder: "+389 70 123 456",
    licensePlatePlaceholder: "SK 1234 AB",

    // Validation Messages
    arrivalDateRequired: "Датумот на пристигање е задолжителен",
    arrivalTimeRequired: "Часот на пристигање е задолжителен",
    departureDateRequired: "Датумот на заминување е задолжителен",
    departureTimeRequired: "Часот на заминување е задолжителен",
    nameRequired: "Името е задолжително",
    emailRequired: "Е-поштата е задолжителна",
    emailInvalid: "Невалидна е-поштенска адреса",
    phoneRequired: "Телефонскиот број е задолжителен",
    phoneInvalid: "Телефонскиот број може да содржи само цифри и + за позивен број (макс. 15 знаци)",
    licensePlateRequired: "Регистарската таблица е задолжителна",
    passengersRequired: "Бројот на патници е задолжителен",
    passengersMin: "Минимум 1 патник",
    passengersMax: "Максимум 8 патници",

    // Invoice Fields
    needInvoice: "Ви треба фактура?",
    yes: "Да",
    no: "Не",
    invoiceDetails: "Податоци за Фактура",
    companyName: "Назив на Компанија",
    companyNamePlaceholder: "ПРИМЕР ДООЕЛ",
    companyNameRequired: "Називот на компанијата е задолжителен",
    companyOwner: "Управител",
    companyOwnerPlaceholder: "Марко Петровски",
    companyOwnerRequired: "Управителот е задолжителен",
    taxNumber: "Даночен Број",
    taxNumberPlaceholder: "123456789",
    taxNumberRequired: "Даночниот број е задолжителен",
    isVAT: "Регистриран за ДДВ",
    vatNumber: "ДДВ Број",
    vatNumberPlaceholder: "МК123456789",
    vatNumberRequired: "ДДВ бројот е задолжителен",
    autoGeneratedVAT: "Автоматски генериран ДДВ број врз основа на даночниот број",
    enterTaxNumberFirst: "Ве молиме внесете даночен број погоре за да се генерира ДДВ број",
    city: "Град",
    selectCity: "Изберете град",
    cityRequired: "Градот е задолжителен",
    address: "Адреса",
    addressPlaceholder: "ул. Примерна 123",
    addressRequired: "Адресата е задолжителна",

    // Contact Form
    haveQuestions: "Имате прашања?",
    inquiryDesc: "Испратете ни го вашето прашање и ќе одговориме колку е можно поскоро",
    name: "Име",
    phoneOptional: "Телефонски Број (Незадолжително)",
    message: "Порака",
    sendInquiry: "Испрати Прашање",
    messagePlaceholder: "Како можеме да ви помогнеме?",
    messageRequired: "Пораката е задолжителна",
    orContactDirectly: "Или контактирајте нè директно:",

    // Discount Code
    discountCode: "Промо Код",
    discountCodePlaceholder: "Внесете промо код",
    discountCodeRequired: "Ве молиме внесете промо код",
    apply: "Примени",
    validating: "Проверка...",
    discountApplied: "Промо кодот е применет! Попуст:",
    discount: "попуст",

    // Toast Messages
    checkDates: "Ве молиме проверете ги датумите и времињата",
    bookingConfirmed: "Резервацијата е потврдена! Износ: €",
    paymentProcessing: ". Обработка на плаќањето...",
    inquirySuccess: "Ви благодариме за прашањето! Наскоро ќе ви се јавиме.",
    spamProtection: "Ве молиме почекајте малку пред повторно да ја испратите формата.",

    // Footer
    footerTagline: "Безбедно, достапно и погодно решение за паркирање",
    footerLocation: "📍 Улица Неделчо Бончев 30, Софија",
    footerRights: "© 2026 SkyParking - Паркинг Аеродром Софија. Сите права задржани.",

    // Map Section
    ourLocation: "Нашата Локација",
    findUs: "Најдете нè лесно близу Терминал 2 на Аеродром Софија",
    takeMeThere: "Навигирај ме",
    takeMeThereWaze: "Навигирај со Waze",
    googleMaps: "Google Maps",
    waze: "Waze",
    howToFindUs: "Како да нè најдете",

    // How It Works Section
    howItWorks: "Како Функционира?",
    onlineTelephoneBooking: "Online / Телефонска Резервација",
    onlineTelephoneBookingText1: "Можете да направите резервација со јавување на",
    onlineTelephoneBookingText2: "или со пополнување на",
    onlineTelephoneBookingText3: ". По завршувањето на резервацијата, ќе ве повикаме за да ги потврдиме сите ваши податоци.",
    bookingForm: "формата за резервација",
    arrivalAndTransfer: "Пристигање на паркингот и трансфер до аеродромот",
    arrivalAndTransferDesc: "При пристигање, нашиот персонал ќе ве пречека и ќе ви помогне со багажот и паркирањето. Потоа ќе го искористите вклучениот трансфер до Аеродром Софија на терминалот по ваш избор — и двата се 5 минути од нашиот паркинг.",
    returnAndPickup: "Враќање и напуштање на паркингот",
    returnAndPickupText1: "Кога ќе го напуштите терминалот и ќе пристигнете до определеното место за трансфер,",
    returnAndPickupText2: " и еден од нашите автобуси ќе дојде да ве земе. Ќе ве одведеме до паркингот каде ќе ве чека вашиот автомобил.",
    callUs: "јавете ни се",
  },
  ro: {
    // Hero Section
    heroTitle: "SkyParking - Parcare Aeroportul Sofia",
    heroSubtitle: "Parcare sigură și accesibilă la 5 minute de Terminalul 1 și 2. Rezervați acum și călătoriți fără griji.",
    bookNow: "Rezervați Acum",
    callButton: "Sunați +359 886 616 991",

    // Navigation
    navFeatures: "Avantaje",
    navBooking: "Rezervare",
    navContact: "Contact",
    navLocation: "Locație",
    navServices: "Servicii",
    navPricing: "Prețuri",
    navHowItWorks: "Cum Funcționează",
    navFAQ: "Întrebări Frecvente",
    navAbout: "Despre Noi",
    callNow: "Sunați",

    // Features
    whyChooseUs: "De ce să alegeți SkyParking?",
    whyChooseUsDesc: "Oferim cea mai fiabilă și convenabilă soluție de parcare pentru pasagerii Aeroportului Sofia",
    secureParking: "Parcare sigură 24/7",
    secureParkingDesc: "Supraveghere video + securitate — mașina dvs. este mereu în siguranță.",
    flexibleHours: "Rezervare ușoară, fără plată în avans",
    flexibleHoursDesc: "Plătiți la sosire — fără taxe suplimentare sau surprize ascunse.",
    airportShuttle: "Transfer gratuit la și de la Aeroportul Sofia",
    airportShuttleDesc: "Rapid și convenabil — doar 5 minute până la Terminalul 1 și 2.",
    allVehicles: "Toate vehiculele",
    allVehiclesDesc: "Acceptăm autoturisme, dube și SUV-uri",
    lowPricesEasyBooking: "Prețuri Mici",
    lowPricesEasyBookingDesc: "Tarife accesibile pentru sejururi scurte și lungi.",

    // Booking Form
    bookYourSpot: "Rezervați Locul",
    reservation: "Rezervare",
    reservationSubtitle: "Fără Plată în Avans · Confirmare prin Telefon",
    bookYourParking: "Rezervați Parcarea",
    datesAndTimes: "Date și Ore",
    yourParkingCost: "Costul Parcării",
    reservationSummary: "Sumar Rezervare",
    duration: "Durată",
    totalCost: "Cost Total",
    noPrePayment: "Fără Plată în Avans – Plătiți la Sosire",
    processing: "Se procesează...",
    fillDetails: "Completați detaliile de mai jos și asigurați-vă locul de parcare",
    arrivalDate: "De la Data",
    arrivalTime: "De la Ora",
    departureDate: "Până la Data",
    departureTime: "Până la Ora",
    estimatedTotal: "Total Estimat",
    finalTotal: "Total Final",
    priceIncludesTransfers: "Prețul include transferuri gratuite",
    days: "zile",
    personalInfo: "Informații Personale",
    fullName: "Nume Complet",
    email: "Email",
    phone: "Număr de Telefon",
    licensePlate: "Număr de Înmatriculare",
    passengers: "Număr de Pasageri",
    proceedToPayment: "Confirmați Rezervarea",
    numberOfCars: "Număr de Mașini",
    car: "mașină",
    cars: "mașini",
    perCar: "pe mașină",
    selectNumberOfCars: "Selectați câte mașini veți parca (pentru grupuri mari sau rezervări corporative)",
    vehicleInformation: "Informații Vehicul",
    passenger: "pasager",
    passengersLabel: "pasageri",
    selectTime: "Selectați ora",
    timesApproximateHelp: "ℹ️ Orele sunt aproximative.\nDacă ajungeți mai devreme sau mai târziu, nu e problemă – sunați-ne.",
    termsAndConditions: "Termeni și Condiții",
    termsAndConditionsLink: "Termenii și Condițiile",
    agreeToTerms: "Sunt de acord cu",
    termsRequired: "Trebuie să acceptați termenii și condițiile",

    // Form Placeholders
    namePlaceholder: "Ion Popescu",
    emailPlaceholder: "ion@example.com",
    phonePlaceholder: "+40 721 123 456",
    licensePlatePlaceholder: "B 123 ABC",

    // Validation Messages
    arrivalDateRequired: "Data de sosire este obligatorie",
    arrivalTimeRequired: "Ora de sosire este obligatorie",
    departureDateRequired: "Data de plecare este obligatorie",
    departureTimeRequired: "Ora de plecare este obligatorie",
    nameRequired: "Numele este obligatoriu",
    emailRequired: "Email-ul este obligatoriu",
    emailInvalid: "Adresă de email invalidă",
    phoneRequired: "Numărul de telefon este obligatoriu",
    phoneInvalid: "Numărul de telefon poate conține doar cifre și + pentru prefix internațional (max. 15 caractere)",
    licensePlateRequired: "Numărul de înmatriculare este obligatoriu",
    passengersRequired: "Numărul de pasageri este obligatoriu",
    passengersMin: "Minimum 1 pasager",
    passengersMax: "Maximum 8 pasageri",

    // Invoice Fields
    needInvoice: "Aveți nevoie de factură?",
    yes: "Da",
    no: "Nu",
    invoiceDetails: "Date Factură",
    companyName: "Numele Companiei",
    companyNamePlaceholder: "EXEMPLU SRL",
    companyNameRequired: "Numele companiei este obligatoriu",
    companyOwner: "Administrator",
    companyOwnerPlaceholder: "Ion Popescu",
    companyOwnerRequired: "Administratorul este obligatoriu",
    taxNumber: "CUI",
    taxNumberPlaceholder: "123456789",
    taxNumberRequired: "CUI-ul este obligatoriu",
    isVAT: "Plătitor de TVA",
    vatNumber: "Număr TVA",
    vatNumberPlaceholder: "RO123456789",
    vatNumberRequired: "Numărul de TVA este obligatoriu",
    autoGeneratedVAT: "Număr TVA generat automat pe baza CUI-ului",
    enterTaxNumberFirst: "Vă rugăm introduceți CUI-ul mai sus pentru a genera numărul TVA",
    city: "Oraș",
    selectCity: "Selectați orașul",
    cityRequired: "Orașul este obligatoriu",
    address: "Adresă",
    addressPlaceholder: "Str. Exemplu 123",
    addressRequired: "Adresa este obligatorie",

    // Contact Form
    haveQuestions: "Aveți Întrebări?",
    inquiryDesc: "Trimiteți-ne solicitarea dvs. și vom răspunde cât mai curând posibil",
    name: "Nume",
    phoneOptional: "Număr de Telefon (Opțional)",
    message: "Mesaj",
    sendInquiry: "Trimiteți Solicitarea",
    messagePlaceholder: "Cum vă putem ajuta?",
    messageRequired: "Mesajul este obligatoriu",
    orContactDirectly: "Sau contactați-ne direct:",

    // Discount Code
    discountCode: "Cod Promoțional",
    discountCodePlaceholder: "Introduceți codul promoțional",
    discountCodeRequired: "Vă rugăm introduceți codul promoțional",
    apply: "Aplică",
    validating: "Verificare...",
    discountApplied: "Cod aplicat! Reducere:",
    discount: "reducere",

    // Toast Messages
    checkDates: "Vă rugăm verificați datele și orele",
    bookingConfirmed: "Rezervare confirmată! Total: €",
    paymentProcessing: ". Se procesează plata...",
    inquirySuccess: "Vă mulțumim pentru solicitare! Vă vom contacta în curând.",
    spamProtection: "Vă rugăm așteptați puțin înainte de a retrimite formularul.",

    // Footer
    footerTagline: "Soluție de parcare sigură, accesibilă și convenabilă",
    footerLocation: "📍 Ulița Nedelcho Bonchev 30, Sofia",
    footerRights: "© 2026 SkyParking - Parcare Aeroportul Sofia. Toate drepturile rezervate.",

    // Map Section
    ourLocation: "Locația Noastră",
    findUs: "Găsiți-ne ușor lângă Terminalul 2 al Aeroportului Sofia",
    takeMeThere: "Navigați",
    takeMeThereWaze: "Navigați cu Waze",
    googleMaps: "Google Maps",
    waze: "Waze",
    howToFindUs: "Cum să ne găsiți",

    // How It Works Section
    howItWorks: "Cum Funcționează?",
    onlineTelephoneBooking: "Rezervare Online / Telefonică",
    onlineTelephoneBookingText1: "Puteți face o rezervare sunând la",
    onlineTelephoneBookingText2: "sau completând",
    onlineTelephoneBookingText3: ". După finalizarea rezervării, vă vom suna pentru a confirma toate datele dvs.",
    bookingForm: "formularul de rezervare",
    arrivalAndTransfer: "Sosire la parcare și transfer la aeroport",
    arrivalAndTransferDesc: "La sosire, personalul nostru vă va întâmpina și vă va ajuta cu bagajele și parcarea mașinii. Apoi veți lua transferul inclus la Aeroportul Sofia la terminalul ales — ambele sunt la 5 minute de parcarea noastră.",
    returnAndPickup: "Întoarcere și plecarea din parcare",
    returnAndPickupText1: "Când plecați de la terminal și ajungeți la zona de transfer desemnată,",
    returnAndPickupText2: " și unul din microbuzele noastre va veni să vă preia. Vă vom duce la parcare unde vă va aștepta mașina.",
    callUs: "sunați-ne",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children, initialLanguage = "bg" }: { children: ReactNode; initialLanguage?: Language }) {
  const [language, setLanguage] = useState<Language>(initialLanguage);

  useEffect(() => {
    setLanguage(initialLanguage);
  }, [initialLanguage]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.bg] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}